controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link_to_torso
      - torso_to_upper_arm
      - upper_arm_to_lower_arm
      - lower_arm_to_hand

    command_interfaces:
      - position

    state_interfaces:
      - position

    allow_partial_joints_goal: true
